-- Optimise les contrôles RLS et les index des clés étrangères sans réduire les permissions.
create index if not exists am_listings_category_idx on public.am_listings(category_id);
create index if not exists am_conversations_listing_idx on public.am_conversations(listing_id);
create index if not exists am_conversations_seller_idx on public.am_conversations(seller_id, updated_at desc);
create index if not exists am_messages_sender_idx on public.am_messages(sender_id);
create index if not exists am_reviews_conversation_idx on public.am_reviews(conversation_id);
create index if not exists am_reviews_to_user_idx on public.am_reviews(to_user_id, created_at desc);
create index if not exists am_identity_verifications_reviewer_idx on public.am_identity_verifications(reviewer_id);

drop policy if exists "am_profile_self_or_admin_read" on public.am_profiles;
drop policy if exists "am_profile_self_update" on public.am_profiles;
drop policy if exists "am_categories_public_read" on public.am_categories;
drop policy if exists "am_categories_admin_inactive_read" on public.am_categories;
drop policy if exists "am_categories_admin_write" on public.am_categories;
drop policy if exists "am_listings_public_read" on public.am_listings;
drop policy if exists "am_listings_owner_or_admin_read" on public.am_listings;
drop policy if exists "am_listings_verified_owner_create" on public.am_listings;
drop policy if exists "am_listings_owner_or_admin_update" on public.am_listings;
drop policy if exists "am_listings_owner_or_admin_delete" on public.am_listings;
drop policy if exists "am_conversations_members_read" on public.am_conversations;
drop policy if exists "am_conversations_buyer_create" on public.am_conversations;
drop policy if exists "am_messages_members_read" on public.am_messages;
drop policy if exists "am_messages_members_create" on public.am_messages;
drop policy if exists "am_reviews_participant_create" on public.am_reviews;
drop policy if exists "am_follows_self_read" on public.am_seller_follows;
drop policy if exists "am_follows_verified_create" on public.am_seller_follows;
drop policy if exists "am_follows_self_delete" on public.am_seller_follows;
drop policy if exists "am_notifications_self_read" on public.am_notifications;
drop policy if exists "am_notifications_self_read_mark" on public.am_notifications;
drop policy if exists "am_verifications_self_read" on public.am_identity_verifications;
drop policy if exists "am_verifications_self_submit" on public.am_identity_verifications;

create policy "am_profile_self_or_admin_read" on public.am_profiles for select to authenticated using (id = (select auth.uid()) or (select am_private.am_is_admin()));
create policy "am_profile_self_update" on public.am_profiles for update to authenticated using (id = (select auth.uid()) or (select am_private.am_is_admin())) with check (id = (select auth.uid()) or (select am_private.am_is_admin()));
create policy "am_categories_anon_public_read" on public.am_categories for select to anon using (active);
create policy "am_categories_authenticated_read" on public.am_categories for select to authenticated using (active or (select am_private.am_is_admin()));
create policy "am_categories_admin_insert" on public.am_categories for insert to authenticated with check ((select am_private.am_is_admin()));
create policy "am_categories_admin_update" on public.am_categories for update to authenticated using ((select am_private.am_is_admin())) with check ((select am_private.am_is_admin()));
create policy "am_categories_admin_delete" on public.am_categories for delete to authenticated using ((select am_private.am_is_admin()));
create policy "am_listings_anon_public_read" on public.am_listings for select to anon using (status = 'published');
create policy "am_listings_authenticated_read" on public.am_listings for select to authenticated using (status = 'published' or owner_id = (select auth.uid()) or (select am_private.am_is_admin()));
create policy "am_listings_verified_owner_create" on public.am_listings for insert to authenticated with check (owner_id = (select auth.uid()) and (select am_private.am_is_verified((select auth.uid()))));
create policy "am_listings_owner_or_admin_update" on public.am_listings for update to authenticated using (owner_id = (select auth.uid()) or (select am_private.am_is_admin())) with check (owner_id = (select auth.uid()) or (select am_private.am_is_admin()));
create policy "am_listings_owner_or_admin_delete" on public.am_listings for delete to authenticated using (owner_id = (select auth.uid()) or (select am_private.am_is_admin()));
create policy "am_conversations_members_read" on public.am_conversations for select to authenticated using (buyer_id = (select auth.uid()) or seller_id = (select auth.uid()) or (select am_private.am_is_admin()));
create policy "am_conversations_buyer_create" on public.am_conversations for insert to authenticated with check (buyer_id = (select auth.uid()) and seller_id <> (select auth.uid()) and (select am_private.am_is_verified(seller_id)) and exists (select 1 from public.am_listings l where l.id = listing_id and l.owner_id = seller_id and l.status = 'published'));
create policy "am_messages_members_read" on public.am_messages for select to authenticated using (exists (select 1 from public.am_conversations c where c.id = conversation_id and (c.buyer_id = (select auth.uid()) or c.seller_id = (select auth.uid()))) or (select am_private.am_is_admin()));
create policy "am_messages_members_create" on public.am_messages for insert to authenticated with check (sender_id = (select auth.uid()) and exists (select 1 from public.am_conversations c where c.id = conversation_id and (c.buyer_id = (select auth.uid()) or c.seller_id = (select auth.uid()))));
create policy "am_reviews_participant_create" on public.am_reviews for insert to authenticated with check (from_user_id = (select auth.uid()) and exists (select 1 from public.am_conversations c where c.id = conversation_id and ((c.buyer_id = from_user_id and c.seller_id = to_user_id) or (c.seller_id = from_user_id and c.buyer_id = to_user_id))));
create policy "am_follows_self_read" on public.am_seller_follows for select to authenticated using (follower_id = (select auth.uid()) or (select am_private.am_is_admin()));
create policy "am_follows_verified_create" on public.am_seller_follows for insert to authenticated with check (follower_id = (select auth.uid()) and seller_id <> (select auth.uid()) and (select am_private.am_is_verified(seller_id)));
create policy "am_follows_self_delete" on public.am_seller_follows for delete to authenticated using (follower_id = (select auth.uid()) or (select am_private.am_is_admin()));
create policy "am_notifications_self_read" on public.am_notifications for select to authenticated using (user_id = (select auth.uid()) or (select am_private.am_is_admin()));
create policy "am_notifications_self_read_mark" on public.am_notifications for update to authenticated using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "am_verifications_self_read" on public.am_identity_verifications for select to authenticated using (user_id = (select auth.uid()) or (select am_private.am_is_admin()));
create policy "am_verifications_self_submit" on public.am_identity_verifications for insert to authenticated with check (user_id = (select auth.uid()));
